# --- Variables ---
DOCKER_COMPOSE = docker compose -f compose.yaml
PHP_CONT       = $(DOCKER_COMPOSE) exec php
CONSOLE        = $(PHP_CONT) bin/console

.PHONY: help run init start stop build all setup bash test stan load-test jwt-keys

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "%-20s %s\n", $$1, $$2}'

# --- Lifecycle ---
run: all ## Full setup and start (default entry point)
	@echo "Application is running at http://localhost:8000"

init: build start jwt-keys ## First time setup: build, start and generate JWT keys
	@echo "Containers are up and JWT keys are ready."
	@echo "Run 'make setup' to install dependencies and prepare the database."

start: ## Start containers in the background
	git checkout compose.yaml 2>/dev/null || true
	$(DOCKER_COMPOSE) up -d

stop: ## Stop containers
	$(DOCKER_COMPOSE) stop

build: ## Rebuild Docker images
	$(DOCKER_COMPOSE) build --no-cache

all: build start jwt-keys setup ## Full build: rebuild images, start containers, generate keys and install dependencies

setup: start jwt-keys ## Full installation from scratch
	@echo "Installing Composer dependencies..."
	$(PHP_CONT) composer install --no-interaction --prefer-dist
	@echo "Cleaning files generated by Symfony recipes..."
	-$(PHP_CONT) rm -f .env.dev compose.override.yaml phpunit.dist.xml .editorconfig symfony.lock config/reference.php
	git checkout compose.yaml 2>/dev/null || true
	@echo "Waiting for the database to be ready..."
	sleep 5
	-$(CONSOLE) doctrine:database:create --if-not-exists
	@echo "Checking for migrations..."
	@MIGRATIONS=$$($(CONSOLE) doctrine:migrations:list --no-interaction 2>/dev/null | grep -c 'App\\Migrations' || echo "0"); \
	if [ "$$MIGRATIONS" -gt "0" ]; then \
		echo "Executing migrations..."; \
		$(CONSOLE) doctrine:migrations:migrate --no-interaction; \
	else \
		echo "No migrations to execute."; \
	fi
	@echo "Preparing test database..."
	-$(CONSOLE) doctrine:database:create --env=test --if-not-exists
	-$(CONSOLE) doctrine:migrations:migrate --env=test --no-interaction
	@echo "Creating default admin user..."
	-$(CONSOLE) app:create-user admin secret123
	@echo "Loading initial events from provider..."
	-$(CONSOLE) app:sync-events
	@echo ""
	@echo "Setup completed. The application is available at http://localhost:8000"
	@echo "Default credentials: admin / secret123"

jwt-keys: ## Generate JWT keys if they do not exist
	@if ! $(PHP_CONT) test -f config/jwt/private.pem; then \
		echo "Generating JWT keys..."; \
		$(PHP_CONT) mkdir -p config/jwt; \
		$(PHP_CONT) openssl genrsa -out config/jwt/private.pem -aes256 -passout pass:1d004a1e052a58cbe371e67617622e6ca476d895349e9a395db885a29d62d18a 4096; \
		$(PHP_CONT) openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem -passin pass:1d004a1e052a58cbe371e67617622e6ca476d895349e9a395db885a29d62d18a; \
		echo "JWT keys generated."; \
	else \
		echo "JWT keys already exist."; \
	fi

bash: ## Access the PHP container
	$(PHP_CONT) bash

# --- Quality and Testing ---
test: ## Run all tests (Unit, Integration, Acceptance)
	$(PHP_CONT) bin/phpunit

stan: ## Run static analysis with PHPStan at level 9
	$(PHP_CONT) vendor/bin/phpstan analyse src -l 9 --memory-limit=512M

load-test: ## Run stress test with k6
	@echo "Running load test..."
	docker run --rm -i --network eventhub_default -e BASE_URL=http://nginx grafana/k6 run - < tests/Load/stress.js

# --- Utilities ---
cache-clear: ## Clear Symfony and Redis cache
	$(CONSOLE) cache:clear
	$(PHP_CONT) redis-cli flushall
