# --- Variables ---
DOCKER_COMPOSE = docker compose -f compose.yaml
PHP_CONT       = $(DOCKER_COMPOSE) exec php
CONSOLE        = $(PHP_CONT) bin/console

.PHONY: help run init start stop build all setup bash test stan load-test jwt-keys app-secret set-env audit

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "%-20s %s\n", $$1, $$2}'

# --- Lifecycle ---
run: all ## Full setup and start (default entry point)
	@echo "Application is running at http://localhost:8000"

init: build start jwt-keys app-secret ## First time setup: build, start and generate JWT keys
	@echo "Containers are up and JWT keys are ready."
	@echo "Run 'make setup' to install dependencies and prepare the database."

start: ## Start containers in the background
	git checkout compose.yaml 2>/dev/null || true
	$(DOCKER_COMPOSE) up -d

stop: ## Stop containers
	$(DOCKER_COMPOSE) stop

build: ## Rebuild Docker images
	$(DOCKER_COMPOSE) build --no-cache

all: build start jwt-keys setup ## Full build: rebuild images, start containers, generate keys and install dependencies

setup: start jwt-keys app-secret ## Full installation from scratch
	@echo "Installing Composer dependencies..."
	$(PHP_CONT) composer install --no-interaction --prefer-dist
	@echo "Cleaning files generated by Symfony recipes..."
	-$(PHP_CONT) rm -f .env.dev compose.override.yaml phpunit.dist.xml .editorconfig symfony.lock config/reference.php
	git checkout compose.yaml 2>/dev/null || true
	@echo "Waiting for the database to be ready..."
	sleep 5
	-$(CONSOLE) doctrine:database:create --if-not-exists
	@echo "Checking for migrations..."
	@MIGRATIONS=$$($(CONSOLE) doctrine:migrations:list --no-interaction 2>/dev/null | grep -c 'App\\Migrations' || echo "0"); \
	if [ "$$MIGRATIONS" -gt "0" ]; then \
		echo "Executing migrations..."; \
		$(CONSOLE) doctrine:migrations:migrate --no-interaction; \
	else \
		echo "No migrations to execute."; \
	fi
	@echo "Preparing test database..."
	-$(CONSOLE) doctrine:database:create --env=test --if-not-exists
	-$(CONSOLE) doctrine:migrations:migrate --env=test --no-interaction
	@echo "Creating default admin user..."
	-$(CONSOLE) app:create-user admin secret123
	@echo "Loading initial events from provider..."
	-$(CONSOLE) app:sync-events
	@echo ""
	@echo "Setup completed. The application is available at http://localhost:8000"
	@echo "Default credentials: admin / secret123"

jwt-keys: ## Generate the JWT key pair and its passphrase if they do not exist
	@if $(PHP_CONT) test -f config/jwt/private.pem; then \
		echo "JWT keys already exist."; \
	else \
		echo "Generating JWT keys and a fresh passphrase..."; \
		PASSPHRASE=$$($(PHP_CONT) openssl rand -hex 32 | tr -d '\r'); \
		$(PHP_CONT) mkdir -p config/jwt; \
		$(PHP_CONT) openssl genrsa -out config/jwt/private.pem -aes256 -passout pass:$$PASSPHRASE 4096; \
		$(PHP_CONT) openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem -passin pass:$$PASSPHRASE; \
		$(MAKE) --no-print-directory set-env FILE=.env.local KEY=JWT_PASSPHRASE VALUE=$$PASSPHRASE; \
		$(MAKE) --no-print-directory set-env FILE=.env.test.local KEY=JWT_PASSPHRASE VALUE=$$PASSPHRASE; \
		echo "JWT keys generated; passphrase written to .env.local and .env.test.local."; \
	fi

app-secret: ## Generate APP_SECRET into .env.local if it is not set yet
	@if grep -qs "^APP_SECRET=..*" .env.local; then \
		echo "APP_SECRET already set."; \
	else \
		SECRET=$$($(PHP_CONT) openssl rand -hex 16 | tr -d '\r'); \
		$(MAKE) --no-print-directory set-env FILE=.env.local KEY=APP_SECRET VALUE=$$SECRET; \
		echo "APP_SECRET generated into .env.local."; \
	fi

# Idempotent upsert of a KEY=VALUE line into a gitignored env file.
set-env:
	@touch $(FILE)
	@grep -v "^$(KEY)=" $(FILE) > $(FILE).tmp 2>/dev/null || true
	@echo '$(KEY)=$(VALUE)' >> $(FILE).tmp
	@mv $(FILE).tmp $(FILE)

bash: ## Access the PHP container
	$(PHP_CONT) bash

# --- Quality and Testing ---
test: ## Run all tests (Unit, Integration, Acceptance)
	$(PHP_CONT) bin/phpunit

stan: ## Run static analysis with PHPStan at level 9
	$(PHP_CONT) vendor/bin/phpstan analyse src -l 9 --memory-limit=512M

audit: ## Check installed dependencies against known vulnerability advisories
	$(PHP_CONT) composer audit

load-test: ## Run stress test with k6 (see tests/Load/README.md)
	@echo "Running load test against the local stack..."
	docker run --rm -i --network eventhub_default -e BASE_URL=http://nginx grafana/k6 run - < tests/Load/stress.js

# --- Utilities ---
cache-clear: ## Clear Symfony and Redis cache
	$(CONSOLE) cache:clear
	$(PHP_CONT) redis-cli flushall
